language: python
python:
- '2.7'
- '3.5'
- '3.6'
sudo: required
services:
- docker
before_install:
- docker pull bigtruedata/gcloud-pubsub-emulator
install:
- pip install -e .
- pip install -e .[dev]
script:
- pycodestyle --ignore=E501 soocii_pubsub_lib
- pytest --cov-report term-missing --cov=soocii_pubsub_lib
after_success:
- coveralls
notifications:
  email:
    on_success: never
    recipients:
      - service@soocii.me
deploy:
  provider: pypi
  user: jonascheng
  password:
    secure: J8zuUA7vOS8s7NemgjBMnw07aLtrc7VfNnDpxLIpR7btENL1miXeytLHArNOSzEIoKeOp96ue0jVPlvrKOFNZ+feqechww6O5mkIFRTPqQk7MNScZIQxvHASvqL+JYL38vbnENIMHiOYEUzs3z8fYWblZ7S4SsLMZTGQ47fuOlob9AthSKIj41Nx4Lfw6Bli0dyA/5KD2YqGBf9kDiaGs1uBmquw2QjEkB5Q4oHqdHeuUtoRhIBsNq9y2uw5ZbGqcl4bKwypPOxKgTvYKg9Xl1OC/JAe/3SrKCYgYlpR3rJGfM+jGSe3oiwwziilTFn93JO380mLNzbh9zpLaEF/Us7j+w8prh62fZewp76+04VEVdLJ0XfaCpSDZSSJ1JZDOl4jmWdOeCh6PyQ0BGkNOPJF6a/a3mCFque2bZzmCHlMnFs43pxaZhqcUbFtHaM/w07YFPhKS5PLIEiEiN7BosjU8rXXOFHBuDKTzSEvOZTt6dWQcCTgOG9Xb9jQEKg+U9LiT2fgCSTuv4cQj2rThmAN/Yz6GBcrrM+Ycg79qebVzRb5qEWOzSz8ddzjPfUPYlsoNBvKPmgVS/7kme0S3Vr4eCh/xjICCREAzuV4qxHrH3TB3okvyLJpQEi6JlUi1myj+UZuI0/jxW4wVUiwUjz8i2zZpZV1DrrXMgaeG3s=
  on:
    branch: master
    tags: true
    python: 3.5
