language: python
python:
- '2.7'
- '3.5'
- '3.6'
sudo: required
services:
- docker
before_install:
- docker pull bigtruedata/gcloud-pubsub-emulator
install:
- pip install -e .
- pip install -e .[dev]
script:
- pycodestyle --ignore=E501 soocii_pubsub_lib
- pytest --cov-report term-missing --cov=soocii_pubsub_lib
after_success:
- coveralls
notifications:
  email:
    on_success: never
    recipients:
    - service@soocii.me
deploy:
  provider: pypi
  user: SoociiDev
  password:
    secure: Hs6tYeD4fX6jC6LzmCPIq4iWgeDFV2uA65MJA+a5ip7vo0lJsriblcAE601uXKz57tmtF+I/btuPshx7R47W9jIeVBvdtqPri8ZDj2PV+3nMwFdHgpp057h3xJ5UBVBMjK9HXTtpR5oIP5lSF7HQ8q/i6E+rJN2ocpL2w+WUq6GmoXyq44JB+FQQuBe/r+6X0lyq9Muz3LRNLlM5528EUSLJ2MaEzqsa/szXkCw8Rj7w01b+zvXsV0+cA4qafco/dZnS/3I/FnlH6NEUCBLewCjHAoa9QGUi3lnLRHm/b1tYlbopRG5uDqTQKCfTkOkEBw8B7TV9jchpLKvYMjo58QJ+U9ag3LvD2d1ci5MOeIgwxz0TLK8O1jp5sdvEdgWdruwIqZhaQyl0L6j0qdZypaEo/+QJQgi6+QmSYcZyki1nvuyRNZIVgogXic6G4zJAEhunQP2vMG+BCJUCl8EVd8jjFqy5e78tLHFrfIv18uimYt+SpL4vBfRXHP2AMZ4LOTwR2XuwTLj/i8SPhAiN+cNd9I9idaISMnDaVMiyaP25je+9D45ACyF/MFbSSjy2zT6yF/lI2IClnhWi+RCIqdkZbavdzvLUl2x+yHI2Ex7nsrM4ipAIURy7tcjfT4IIUddBODEiIfKNkJmrEyOxJIxV7MwOtnabEvRfx//GYFs=
  on:
    branch: master
    tags: true
    python: 3.5
